#!/usr/bin/python
# -*- coding: utf-8 -*-
# --------------------------------------------------------------------------
# Programa que tiene como entrada un archivo html con tags de codigo shinyEL.
# Realiza el analisis lexicografico y sintactico de los fragmentos shinyEL. 
#
# Devuelve una representacion intermedia del codigo html con marcas en donde 
# aparecen los tags de shinyEL. Y construye el grafo de dependencias. 
#
# Version 0.1
#
# Autores : Hancel Gonzalez   07-40983
#           Jennifer Dos Reis 08-10323
#
# -------------------------------------------------------------------------

import lexer_parser
import ply.lex as lex
import ply.yacc as yacc
import networkx as nx
import matplotlib.pyplot as plt
import copy
import sys
import os

###############################################################
##########    METODOS PARA CALCULAR LOS TIPOS        ##########
###############################################################

######## TIPOS PARA OPERADORES BINARIOS ##########
def calcularTipoOpBin(expr,expr1,expr2,var):

    if isinstance(expr,lexer_parser.Suma):
        if expr1.tipo==expr2.tipo:
            expr.tipo= expr1.tipo
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
                print "Error de tipos en la variable '"+var+ "'.\n '+': esperaba tipos compatibles"
                error=True
            expr.tipo="tipo_error"
    elif isinstance(expr,lexer_parser.Resta):
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="int"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
                print "Error de tipos en la variable '"+var+ "'.\n '-': esperaba tipos int"
                error=True
            expr.tipo="tipo_error"
    elif isinstance(expr,lexer_parser.Producto):
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="int"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
                print "Error de tipos en la variable '"+var+ "'.\n '*': esperaba tipos int"
                error=True
            expr.tipo="tipo_error"
   
    elif isinstance(expr,lexer_parser.Division):
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="int"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
               print "Error de tipos en la variable '"+var+ "'.\n '/': esperaba tipos int"
               error=True
            expr.tipo="tipo_error"
            
    elif isinstance(expr,lexer_parser.Mod):
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="int"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
                 print "Error de tipos en la variable '"+var+ "'.\n '%': esperaba tipos int"
                 error=True
            expr.tipo="tipo_error"

    elif isinstance(expr,lexer_parser.Potencia):
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="int"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
               print "Error de tipos en variable '"+var+"'.\n '**': esperaba tipos int"
               error=True
            expr.tipo="tipo_error"
            
    elif isinstance(expr,lexer_parser.OpBool):
        tipoExp1= ''
        tipoExp2= ''
        if isinstance(expr1,str):
            tipoExpr1= "bool" if ((expr1=="true") or (expr2=="false")) else "error"
        else:
            tipoExpr1=expr1.tipo

        if isinstance(expr2,str):
            tipoExpr2= "bool" if ((expr1=="true") or (expr2=="false")) else "error"
        else:
            tipoExpr2=expr2.tipo
            
        if (tipoExpr1=="bool") & (tipoExpr2=="bool"):
            expr.tipo="bool"
        else:
            if (tipoExpr1!="tipo_error") & (tipoExpr2!="tipo_error"):
                print "Error de tipos en la variable '"+var+"'.\n Operador booleano: esperaba tipos bool"
                error=True
            expr.tipo="tipo_error"
            
    elif isinstance(expr,lexer_parser.Comparacion):
        
        if (expr1.tipo=="int") & (expr2.tipo=="int"):
            expr.tipo="bool"
        else:
            if (expr1.tipo!="tipo_error") & (expr2.tipo!="tipo_error"):
                print "Error de tipos en variable '"+var+"'.\n Operador de comparacion: esperaba tipos int"
                error=True
            expr.tipo="tipo_error"
        
###### TIPO DE UNA LISTA #######    
def calcularTipoLista(lista,var):
    if (len(lista.list)==0):
        lista.tipo= "list of"
    else:
        type=lista.list[0].tipo
        if (type!="int") & (type!="string"):
            lista.tipo="tipo_error"
            error=True
            print "Error de tipos en la variable "+var+".\n Se esperaba una lista de ints o strings"

        t= True
        for elem in lista.list:
            t= (type==elem.tipo) & t           
            if (elem.tipo=="tipo_error"):
                lista.tipo= "tipo_error"
                return
        if (t):
            lista.tipo= "list of "+type
        else:
            lista.tipo="tipo_error"
            print "Error de tipos en la variable "+var+".\nSe esperaba una lista homogenea de tipo '"+type+"'" 
            error=True

###### TIPOS PARA LOS OPERADORES UNARIOS ######          
def calcularTipoUnOp(expresion,operando,var):
    if isinstance(expresion,lexer_parser.Neg):
        if isinstance(operando,str):
             expresion.tipo="bool" if(operando=="true")or(operando=="false") else "error"
             if expresion.tipo=="error": print "Error!"
        elif operando.tipo=="bool":
            expresion.tipo="bool"
        elif operando.tipo=="tipo_error":
            expresion.tipo="tipo_error"
        else:
            error=True
            expresion.tipo="tipo_error"
            print "Error de tipos en la variable '"+var+"'\n'!': Esperaba expresion de tipo bool "
    else:
        if operando.tipo=="int":
            expresion.tipo="int"
        elif operando.tipo=="tipo_error":
            expresion.tipo="tipo_error"
        else:
            error=True
            expresion.tipo="tipo_error"
            print "Error de tipos en la variable '"+var+"'\n'-': Esperaba expresion de tipo int "

def calcularTipoCuant(cuant,op,var,listOTable,expr):
    # Casos a considerar:
    # 1. [% op var : list : expr%] tipo de la expr
    # 2. [%    var : list : expr%] list of (tipo de la expr)
    # 3. [% op var: table: expr %] tipo de la expr
    # 4. [%    var: table: expr %] list of (tipo de la expr)

    if (op==''):
        # Caso 2 y 4: 'listas'
        if expr.tipo=="int":
            cuant.tipo="list of int"
        elif expr.tipo=="string":
            cuant.tipo="list of string"
        elif expr.tipo=="table":
            hola=1
        elif expr.tipo=="list of int":
            holh=0
        elif expr.tipo=="list of string":
            gol=0
        #if varCuant[var]=="opcional":
         #   cuant.tipo="list of"
        
        # Caso 1 y 4

def setTipoVar(expr): 
    # El tipo de la variable del cuantificador depende del tipo de la lista
    if expr.list.tipo=="list of int":     
        varCuant[expr.var]="int"
    elif expr.list.tipo=="list of string":
        varCuant[expr.var]="string"
    elif expr.list.tipo=="list of":
        varCuant[expr.var]="opcional"
    elif expr.list.tipo=="table":
        varCuant[expr.var]="table"
    elif expr.list.tipo=="int":
        print"Error de tipo en la variable'"+expr.var+"'se esperaba list o table"
        expr.tipo="tipo_error"
        error=True
        return False
    elif expr.list.tipo=="string":
        print "Error de tipo en la variable "+expr.var+" se esperaba list o table"
        expr.tipo="tipo_error"
        error=True
        return False
    else:
        varCuant[expr.var]="tipo_error"
        return False
    return True

######### TIPOS PARA LOS ACCESOS A LISTAS ############
def calcularTipoAccList(expr,var):

    if (expr.var.tipo=="list of int") & (expr.index.tipo=="int"):
        expr.tipo="int"
    elif (expr.var.tipo=="list of string") & (expr.index.tipo=="int"):
        expr.tipo="string"
    elif (expr.index.tipo!="int") & (expr.index.tipo!="tipo_error"):
        print "Error de tipo en la variable"+var+".\n En el acceso a la lista se esperaba un index de tipo 'int'"
        expr.tipo="tipo_error"
    elif (expr.var.tipo!="list of int")&(expr.var.tipo!="list of string") & (expr.var.tipo!="tipo_error"):
        print "Error de tipo en la variable"+var+".\n Var '"+expr.var.var+"': Se esperaba que fuera de tipo 'list of ..'"
    else:
        expr.tipo="tipo_error"
            
# Funcion que recibe el nombre de una variable var y una expresion expr.
# Va anadiendo arcos que van desde las variables que se encuentran dentro
# de la expresion expr hasta la variable var en el grafo declarado como
# variable global GD (Grafo de dependencias). Y calcula el tipo de las 
# expresiones  
def recorrer(var,expr):
    global nro
    global varCuant
    global contextCuant
    global error

    if isinstance(expr,lexer_parser.BinOp):
        # op1 opBinnario op2
        recorrer(var,expr.op1)
        recorrer(var,expr.op2)
        calcularTipoOpBin(expr,expr.op1,expr.op2,var)
    elif isinstance(expr,lexer_parser.UnOp):
        # opUnario(op)
        recorrer(var,expr.op)
        calcularTipoUnOp(expr,expr.op,var)
    elif isinstance(expr,lexer_parser.IfExp):
        # Expresion IF cond THEN expr1 ELSE expr2  
        recorrer(var,expr.cond)
        recorrer(var,expr.exp1)
        recorrer(var,expr.exp2)
        if isinstance(expr.cond,str):
            if ((expr.cond=="true") | (expr.cond=="false")) &  (expr.exp1.tipo==expr.exp2.tipo):
                expr.tipo=expr.exp1.tipo
                return
        if (expr.cond.tipo=="bool") & (expr.exp1.tipo==expr.exp2.tipo):
            expr.tipo=expr.exp1.tipo
        else:
            expr.tipo="tipo_error"
    elif isinstance(expr,lexer_parser.AccList):
        # Acceso a lista: var[index]
        recorrer(var,expr.index)
        recorrer(var,expr.var)
        calcularTipoAccList(expr,var)
    elif isinstance(expr,lexer_parser.AccTab):
        # Acceso a tabla: var[index].col
        recorrer(var,expr.index)
        recorrer(var,expr.var)
        if (expr.index.tipo=="int" | expr.index==0) & (expr.var.tipo=="table"):
            expr.tipo=expr.col.tipo
        else:
            expr.tipo="tipo_error"
    elif isinstance(expr,lexer_parser.Range):
        # Funcion range(ini,fin)
        recorrer(var,expr.ini)
        recorrer(var,expr.fin)
        if (expr.ini.tipo=="int") & (expr.fin.tipo=="int"):
            expr.tipo="list of int"
        else:
            expr.tipo="tipo_error"
    elif isinstance(expr,lexer_parser.Len):
        # Funcion Len(var)
        recorrer(var,expr.var)
        if (expr.var.tipo == "list of int") | (expr.var.tipo=="list of string")|(expr.var.tipo=="list of"):
            expr.tipo="int"
        else:
            expr.tipo= "tipo_error"
    elif isinstance(expr,lexer_parser.List):
        # Recorrer cada elemento de la lista
        for elem in (expr.list):
            recorrer(var,elem)
        calcularTipoLista(expr,var)    
    elif isinstance(expr,lexer_parser.Cuant):
        # Cuantificador: [% op var: L : exp %]
        recorrer(var,expr.list)
        contextCuant=True
        ok= setTipoVar(expr)
        if not(ok):
            return 
        # Calcular el tipo de la expresion tomando en cuenta el tipo de var
        recorrer(var,expr.exp)
        calcularTipoCuant(expr,expr.op,expr.var,expr.list,expr.exp)
        GD.remove_node(var)
    elif isinstance(expr,lexer_parser.Var):
        # Caso base: expr es una variable
        if(contexTabla):
            if (expr.var in diccTabla):
                tabla=nombreTabla
                GD.add_edge(tabla+"."+expr.var,var)
                expr.tipo= diccTabla[expr.var][0]
            else:
                GD.add_edge(expr.var,var)
                # Buscar el tipo de la variable en la tabla de simbolos
######################### Si no se encuentra error !! Y que fuera del contexto
######################### no exista un var.var
########################## El tipo de una variable puede ser "opcional" cuidado
#### Si estoy en el contexto de un cuantificador revisar todas las variables primero en el diccionario 
                expr.tipo= table[expr.var][0]
        else:
            GD.add_edge(expr.var,var)
            # Buscar el tipo de la variable en la tabla de simbolos
            expr.tipo= table[expr.var][0]
                
    elif isinstance(expr,lexer_parser.Num):
        expr.tipo= "int"
    elif isinstance(expr,lexer_parser.String):
        expr.tipo="string"
        
    elif expr == 'input':       
        table['_e' + str(nro+1)] = ('',expr)
        GD.add_edge('_e' + str(nro+1),var)
        nro= nro+1


###########################################################################
###############                   MAIN                    #################
###########################################################################
lexer = lex.lex(module=lexer_parser)
parser = yacc.yacc(module=lexer_parser,start='program',errorlog=yacc.NullLogger())

# Tabla de simbolos global
global table 
table= {}
# Numero de la siguiente expresion
global nro
nro=0
# Variable que indica si se esta en el contexto de un cuantificador
contexCuant=False
# Si se esta dentro del contexto de un cuantificador 'varCuant' contiene
# una lista de las variables dentro del cuantificador con sus tipos respectivos
varCuant= {}
# Existio algun error de tipo
error= False

data = sys.argv[1]
file = open(data,"r")
salida = file.name[:-3] + "html"
file_e = open(salida,"w")

# Reconocimiento de los bloques correspondientes a codigo shinyEL
tables = []
i = 1
tag_html= {}
while True:
    b = ''
    bl = False
    s1 = file.read(1)
    if len(s1) == 0 :
        break    
    if s1 == '{':
        s1 = file.read(1)
        if s1=='%':
            marca_shiny = '&(marcha_shiny_'+str(i)+')'
            # Escritura de la marca shiny en nuevo archivo html
            file_e.write(marca_shiny)
            while True:	
                s1 = file.read(1)
                if s1 == '%':
                    s2 = file.read(1)
                    if  s2 == '}':
                    	bl = True
                    	i += 1
                    	break
                    else:
                        b = b + s1 + s2
                else:
                     b = b + s1
        else:
            print "Falta un caracter % en la expresion "  + str(i) + ". Se espera '{%'"
            file_e.close()
            os.remove(salida)
            exit(1)
    else:
        file_e.write(s1)
        # Analisis del bloque de codigo
    if bl and b != '':
        lexer.input(b)
        #for tok in lexer: print tok
        result = parser.parse(b)
        print b
	exp= result[0]
	if isinstance(exp,lexer_parser.SalidaExpresion):
            nro = nro + 1
            id = '_e'+str(nro) 
            table[id] = ('',exp.exp)
            if exp.exp == 'input':
                tag_html[marca_shiny] = lexer_parser.html_input(id)
            else:
                tag_html[marca_shiny] = lexer_parser.html_span(id)
            print exp.exp
        else:
            print exp.exp
            tag_html[marca_shiny] = exp.html()
            for d in exp.exp:
                print d
        # Se aniade la tabla de simbolo del bloque a una lista
        tables.append(result[1])
        if result[2]: error=True
        
       
file_e.seek(0)
intermedio= file_e.read()

for tag in tag_html:
    tmp = ''    
    if isinstance(tag_html[tag],list):
        for t in tag_html[tag]:
            tmp = tmp + t + "\n"
        intermedio = intermedio.replace(tag,tmp)
    else:
        intermedio = intermedio.replace(tag,tag_html[tag])

file_e.seek(0)
file_e.write(intermedio)
file_e.close()

#########################################
# Union de las tablas a la tabla global #
#########################################

for tab in tables:
    for var in tab.keys():
        if var in table:
            print "Error: Variable '"+ var+"' declarada mas de una vez"
            os.remove(salida)
            error= True
        table[var]= tab[var]
if(error): exit(1)           

#######################################
###  Crear grafo de dependencias   ####
#######################################

global GD
GD = nx.DiGraph()

# Variable booleana que identifica si se esta dentro del
# contexto de una tabla
global contexTabla
contexTabla= False

# Si la variable contexTabla es True diccTabla contiene el
# diccionario de variables contenidas dentro de la tabla y
# nombreTabla contiene el nombre de la misma
global diccTabla
global nombreTabla

for var in table.copy():
    # Si el tipo de la variable es 'table'
    if table[var][0]=="table":
        contexTabla=True
        diccTabla= table[var][1]
        nombreTabla= var
        for varT in table[var][1].keys():	
            recorrer(var+"."+ varT,table[var][1][varT][1])
        contexTabla=False
    else:
        recorrer(var,table[var][1])

# If error=True hay error y no traducir nada.		
print table

#print lexer_parser.Dec("a","int",lexer_parser.Num(1)).eval()
			
nx.draw(GD)
plt.show()
